import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { TestComponent } from '../components/test-component';
import { Button, Grid, List, Stack } from '@mui/material';


const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Grid
            container
            height="100vh"
            alignItems="center"
            justifyContent="center"
            direction="column"
          >
            <h1>Using Material UI with Next.js 13</h1>
            <TestComponent />
            <Stack direction="row" columnGap={1}>
              <Button variant="text" className={styles.btnTest}>
                Text
              </Button>
              <Button variant="contained">Contained</Button>
              <Button variant="outlined">Outlined</Button>
            </Stack>
          </Grid>
      </main>
    </>
  );
}
